### PR TITLE
Enable ginkgolinter

### PR DESCRIPTION
**Pull request by bshewale**

### CODE REVIEW

**Comment by bshewale** [comment]
this pr is depends-on: https://github.com/openshift/release/pull/38533

**Comment by mrKisaoLamb** [comment]
Hey, it looks like the version of golangci-linter is too old for ginkgolinter and needs to be updated to v1.51 based on the documentation at https://golangci-lint.run/usage/linters/. Additionally, I think there's no need to run golangci-lint in two jobs (it seems to be running in both the golangci job and the pre-commit job)

**Comment by bshewale** [comment]
> Hey, it looks like the version of golangci-linter is too old for ginkgolinter and needs to be updated to v1.51 based on the documentation at https://golangci-lint.run/usage/linters/. Additionally, I think there's no need to run golangci-lint in two jobs (it seems to be running in both the golangci job and the pre-commit job)

yeah we are usinf v1.52.1 here https://github.com/openstack-k8s-operators/ovn-operator/blob/main/.pre-commit-config.yaml#L69

**Review by booxter — APPROVED** [review]

**Comment by abays** [comment]
The `ci/prow/functional` has been waiting for about a day now.  That doesn't seem right.

**Comment by bshewale** [comment]
> The `ci/prow/functional` job has been waiting for about a day now. That doesn't seem right.

Hey after recheck it passed, may be we can merge this PR.

**Review by gibizer — APPROVED** [review]
looks good to me.

**Review by karelyatin — APPROVED** [review]
/lgtm

**Pull request merged**
