### PR TITLE
update csv for fips-compliant

### PR DESCRIPTION
**Pull request by yazug**
change introduced in
https://github.com/openstack-k8s-operators/ovn-operator/pull/289

this was generated from left over results of make bundle

### CODE REVIEW

**Comment by booxter** [comment]
recheck

```
Resource: "machineconfiguration.openshift.io/v1, Resource=machineconfigs", GroupVersionKind: "machineconfiguration.openshift.io/v1, Kind=MachineConfig"
Name: "rendered-master-6b590ad6639d660b527ed8ea1f4a8e25", Namespace: ""
for: "/var/home/core/machineconfigpool/updated-rendered-master-6b590ad6639d660b527ed8ea1f4a8e25.yaml": error when patching "/var/home/core/machineconfigpool/updated-rendered-master-6b590ad6639d660b527ed8ea1f4a8e25.yaml": Operation cannot be fulfilled on machineconfigs.machineconfiguration.openshift.io "rendered-master-6b590ad6639d660b527ed8ea1f4a8e25": the object has been modified; please apply your changes to the latest version and try again
```

**Review by karelyatin — APPROVED** [review]
/lgtm

**Pull request merged**
