### PR TITLE
Reset connection when turning off TLS

### PR DESCRIPTION
**Pull request by olliewalsh**
Jira: [OSPRH-10415](https://issues.redhat.com//browse/OSPRH-10415)

### CODE REVIEW

**Comment by booxter** [comment]
The code looks correct. Should we add a kuttl test to validate that tls disabled removes the records? (Not sure it affects more than that. Does the service still start successfully if these records are left lingering?)

**Comment by olliewalsh** [comment]
> The code looks correct. Should we add a kuttl test to validate that tls disabled removes the records? (Not sure it affects more than that. Does the service still start successfully if these records are left lingering?)

Basic tests work for me at least -  Disabling podLevel TLS on the controlplane and dataplane succeeds, previously neutronapi would fail to connect the the sb db.

**Pull request closed without merging**
