### PR TITLE
Remove the double update when finalizer added

### PR DESCRIPTION
**Pull request by gibizer**
The northd and dbcluster controller did a separate client.Update after
it added the self finalizer then returned and run the defer call that
did another client.Patch. However the first client.Update only wrote the
main resource and ignored the status subresource. However it refreshed
the whole instance with the result of the Update meaning it reset the in
memory status updates. We don't need two separate update so this PR
removes the standalone Update and rely on the deferred Patch call to
do all the update.

### CODE REVIEW

**Comment by booxter** [comment]
/lgtm

indeed, the client will just override the whole thing from response, regardless of which subresources were touched: https://github.com/kubernetes/client-go/blob/master/rest/request.go#L1360

**Comment by gibizer** [comment]
/test ovn-operator-build-deploy-kuttl

```
failed to wait for the created cluster claim to become ready: timed out waiting for the condition
```

**Comment by booxter** [comment]
recheck

```
failed to wait for the created cluster claim to become ready: timed out waiting for the condition
```

**Comment by gibizer** [comment]
/test ovn-operator-build-deploy-kuttl


```
{  failed to wait for the created cluster claim to become ready: timed out waiting for the condition}

```

**Pull request merged**
