### PR TITLE
Revert "Add support for adding multiple networkattachments to the ovn…

### PR DESCRIPTION
**Pull request by elvgarrui**
…controller pods"

This reverts commit 5aea578acbfedc1483f2feef64e06213c7963a15.

Seems like NetworkAttachments won't be used by Octavia in the end, so reverting the code to align this property with the other openstack-k8s-operator repos.

Original PR: https://github.com/openstack-k8s-operators/ovn-operator/pull/174

### CODE REVIEW

**Comment by elvgarrui** [comment]
I think the failure is legit. Looking into it now.

`OVNController controller [38;5;243mwhen OVNController and OVNDBClusters are created with networkAttachments [38;5;9m[1m[It] reports that an IP is missing [0m`

**Comment by elvgarrui** [comment]
recheck
I was not able to reproduce this failure on my environment. Maybe it is a flaky test.

**Review by karelyatin — APPROVED** [review]
/lgtm

**Pull request merged**
